### ISSUE TITLE
Domain modling

### ISSUE THREAD

**Issue by tomhalson** [Memstack/Memstack#4]

**Comment by sc14aec** [comment]
https://www.lucidchart.com/documents/edit/bbfa1484-ad54-4bfa-8cac-33f5afef2c98/0?shared=true&

**Comment by sc14aec** [comment]
Key schema and access patterns:
https://docs.google.com/spreadsheets/d/1quK8X19EFZOkEI4a9AASAOzlxNaMcqrRWVaJRmGoz_c/edit#gid=0
